jobs:
  build:
#    working_directory: /circleci-example
    docker:
      - image: bash
    steps:
      - checkout
      - run: ./build.sh

  deploy_to_dev:
    docker:
      - image: bash
    steps:
      - checkout
      - run: ./deploy.sh dev

  integration_test:
    docker:
      - image: bash
    steps:
      - checkout
      - run: ./integration_test.sh

  acceptance_test:
    docker:
      - image: bash
    steps:
      - checkout
      - run: ./acceptance_test.sh

  deploy_to_perf:
    docker:
      - image: bash
    steps:
      - checkout
      - run: ./deploy.sh qa

  perf_test:
    docker:
      - image: bash
    steps:
      - checkout
      - run: ./perf_test.sh

  deploy_to_prod:
    docker:
      - image: bash
    steps:
      - checkout
      - run: ./deploy.sh prod

workflows:
  version: 2
  build-push-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy_to_dev:
          requires:
            - build
      - integration_test:
          requires:
            - build
      - acceptance_test:
          requires:
            - build
      - deploy_to_perf:
          requires:
            - build
      - perf_test:
          requires:
            - deploy_to_perf
      - qa_sign_off:
          type: approval
          requires:
            - integration_test
            - acceptance_test
            - perf_test
      - manually_approve_deploy_to_prod:
          type: approval
          requires:
            - qa_sign_off
      - deploy_to_prod:
          requires:
            - manually_approve_deploy_to_prod
